In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
df = pd.read_csv('suburbs.csv')

df['suburb'] = df['0'].apply(lambda x : '+'.join(x.split('-')[:-2]))
len(df['suburb'])

15879

In [3]:
df

,0,source,suburb
0,oaks-tas-7303,https://www.domain.com.au/suburb-profile/,oaks
1,gibraltar-range-nsw-2370,https://www.domain.com.au/suburb-profile/,gibraltar+range
2,bulli-creek-qld-4357,https://www.domain.com.au/suburb-profile/,bulli+creek
3,gurindji-nt-0852,https://www.domain.com.au/suburb-profile/,gurindji
4,buckenderra-nsw-2630,https://www.domain.com.au/suburb-profile/,buckenderra
...,...,...,...
15874,bindi-vic-3896,https://www.domain.com.au/suburb-profile/,bindi
15875,mongarlowe-nsw-2622,https://www.domain.com.au/suburb-profile/,mongarlowe
15876,teal-point-vic-3579,https://www.domain.com.au/suburb-profile/,teal+point
15877,macdonalds-creek-nsw-2339,https://www.domain.com.au/suburb-profile/,macdonalds+creek
15878,branch-creek-qld-4625,https://www.domain.com.au/suburb-profile/,branch+creek

In [ ]:
url = "https://www.realestateinvestar.com.au/Property/oaks"
response = requests.get(url)

soup = BeautifulSoup(response.content, 'html.parser')
    
print(soup.prettify())

In [16]:
for i in soup.find_all(class_="tab-content guides pt30 white-content")[0].find_all(class_='tab-pane'):
    print(i.text)
    print('*'*50)

NA
Current vacancy rate






0
Rental stock available






35
Population






62.50%
Rental population






**************************************************




0.38%
Current vacancy rate






38
Rental stock available






19,279
Population






19.02%
Rental population






**************************************************




0.70%
Current vacancy rate






1,916
Rental stock available






509,956
Population






23.11%
Rental population






**************************************************