In [3]:
import pandas as pd

In [4]:
df = pd.read_excel('GMAT_Al_Qs.xlsx')
df

,question_id,main_question_stem,subquestion1,subquestion2,subquestion3,answer_1,answer_2,answer_3,answer_4,answer_5,correct_answer,Category,Sub-category,Quant_category 1,Quant_category 2,level
0,1,"In a locality, there are thrice as many buses ...",NaN,NaN,NaN,0.225,0.25,0.3,0.333,0.36,A,Quant,Percentage,Word problems,Arithmetic,1
1,2,"In a school, 20% of the boys learn French whil...",NaN,NaN,NaN,20,24,30,36,45,C,Quant,Percentage,Word problems,Arithmetic,1
2,1,A and B need to do the laundry since their was...,NaN,NaN,NaN,1/12,1/9,1/8,1/6,1/3,B,Quant,Rate and Work,Word problems,Arithmetic,1
3,2,"A can write 10 programming codes in 15 hours, ...",NaN,NaN,NaN,1/5,3/10,1/3,9/20,1/2,D,Quant,Rate and Work,Word problems,Arithmetic,1
4,3,A and B can paint 3 walls in 2 hours. Along wi...,NaN,NaN,NaN,1.5 hours,1.8 hours,2 hours,2.5 hours,3 hours,A,Quant,Rate and Work,Word problems,Arithmetic,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
531,37,"A new kind of primate, the fat-tailed lemur, h...",NaN,NaN,NaN,The statement challenges the long-held belief ...,The statement accuses scientists who have stud...,The statement highlights the importance of thi...,The statement calls into question the assumpti...,The statement sets up a rival theory so that t...,C,Verbal,Critical Reasoning,NaN,NaN,4
532,38,"When we think about peoples of the past, we in...",NaN,NaN,NaN,we intuitively try to imagine what he or she w...,we intuitively try to imagine what they would ...,we intuitively try to imagine what he or she w...,we intuitively try to imagine what they would ...,we intuitively try to imagine what they would ...,B,Verbal,Sentence Correction,NaN,NaN,1
533,39,Motorcyclists are told to always wear helmets ...,NaN,NaN,NaN,"My European client calls once a week, always i...",This sunscreen allows me to stay in the sun 15...,"The odds are 1,000 to 1 against winning the bi...",Seat belts protect passengers in auto - mobile...,Top business schools accept one out of every 2...,A,Verbal,Sentence Correction,NaN,NaN,4
534,40,Even though Carter had fewer quarters in his p...,NaN,NaN,NaN,Even though Carter had fewer quarters in his p...,Even though Carter had fewer quarters than his...,Even though Carter had less quarters than his ...,Even though Carter had less quarters in his pi...,Even though Carter had fewer quarters than his...,A,Verbal,Sentence Correction,NaN,NaN,1
535,41,Rugby is somewhat like American football in th...,NaN,NaN,NaN,Rugby is somewhat like American football in th...,Rugby is somewhat like American foot - ball in...,Rugby is somewhat like American football in th...,Rugby is somewhat like American football in th...,Rugby is somewhat like American football in th...,C,Verbal,Sentence Correction,NaN,NaN,2

In [5]:
df.index = range(1, len(df) + 1)
df

,question_id,main_question_stem,subquestion1,subquestion2,subquestion3,answer_1,answer_2,answer_3,answer_4,answer_5,correct_answer,Category,Sub-category,Quant_category 1,Quant_category 2,level
1,1,"In a locality, there are thrice as many buses ...",NaN,NaN,NaN,0.225,0.25,0.3,0.333,0.36,A,Quant,Percentage,Word problems,Arithmetic,1
2,2,"In a school, 20% of the boys learn French whil...",NaN,NaN,NaN,20,24,30,36,45,C,Quant,Percentage,Word problems,Arithmetic,1
3,1,A and B need to do the laundry since their was...,NaN,NaN,NaN,1/12,1/9,1/8,1/6,1/3,B,Quant,Rate and Work,Word problems,Arithmetic,1
4,2,"A can write 10 programming codes in 15 hours, ...",NaN,NaN,NaN,1/5,3/10,1/3,9/20,1/2,D,Quant,Rate and Work,Word problems,Arithmetic,1
5,3,A and B can paint 3 walls in 2 hours. Along wi...,NaN,NaN,NaN,1.5 hours,1.8 hours,2 hours,2.5 hours,3 hours,A,Quant,Rate and Work,Word problems,Arithmetic,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
532,37,"A new kind of primate, the fat-tailed lemur, h...",NaN,NaN,NaN,The statement challenges the long-held belief ...,The statement accuses scientists who have stud...,The statement highlights the importance of thi...,The statement calls into question the assumpti...,The statement sets up a rival theory so that t...,C,Verbal,Critical Reasoning,NaN,NaN,4
533,38,"When we think about peoples of the past, we in...",NaN,NaN,NaN,we intuitively try to imagine what he or she w...,we intuitively try to imagine what they would ...,we intuitively try to imagine what he or she w...,we intuitively try to imagine what they would ...,we intuitively try to imagine what they would ...,B,Verbal,Sentence Correction,NaN,NaN,1
534,39,Motorcyclists are told to always wear helmets ...,NaN,NaN,NaN,"My European client calls once a week, always i...",This sunscreen allows me to stay in the sun 15...,"The odds are 1,000 to 1 against winning the bi...",Seat belts protect passengers in auto - mobile...,Top business schools accept one out of every 2...,A,Verbal,Sentence Correction,NaN,NaN,4
535,40,Even though Carter had fewer quarters in his p...,NaN,NaN,NaN,Even though Carter had fewer quarters in his p...,Even though Carter had fewer quarters than his...,Even though Carter had less quarters than his ...,Even though Carter had less quarters in his pi...,Even though Carter had fewer quarters than his...,A,Verbal,Sentence Correction,NaN,NaN,1
536,41,Rugby is somewhat like American football in th...,NaN,NaN,NaN,Rugby is somewhat like American football in th...,Rugby is somewhat like American foot - ball in...,Rugby is somewhat like American football in th...,Rugby is somewhat like American football in th...,Rugby is somewhat like American football in th...,C,Verbal,Sentence Correction,NaN,NaN,2

In [9]:
df.to_excel('gmat_all_qs.xlsx')

In [3]:
df.to_csv('gmat_all_qs.csv',index = False)